### ISSUE TITLE
is "tot_sites" the length of the whole genome?

### ISSUE THREAD

**Issue by TeresaPegan** [fgvieira/ngsDist#12]
Hi,
Hopefully this is a pretty simple question -- I would like to confirm my interpretation of  "n_sites" and "tot_sites." 
>--n_sites INT: number of sites in input file.
>--tot_sites INT: total number of sites in dataset.

I guess it depends on what is meant by the "dataset." At first I thought of my dataset as being my beagle file, but that is really the input file (so the number of sites in the beagle file goes into n_sites.) 

I see in the ngsDist Biol J Linn Soc reference that
> we finally rescaled these distances to the total sequence length to correct for ascertainment bias.
I assume that is what is done with tot_sites.

So, should tot_sites be the reference genome length of my study organism if I want to rescale the distances? 

Thanks!
-Teresa

**Comment by fgvieira** [comment]
Hi Teresa,

Since the `beagle` file usually only has SNPs, it can be misleading if you calculate a genetic distance from it. To account for that, `ngsDist` allows you to specify the total number of sites that your sequenced (`tot_sites`).

It can be the reference genome length (if you used the entire genome), the length of the non-missing fraction of the reference genome (if it has a lot of `N`s), the sum of all the targeted regions (if you did targeted sequencing), etc...

It might also not be super relevant, if you are only interested on relative distances between samples.

**Comment by TeresaPegan** [comment]
Thanks, that makes sense!
