### ISSUE TITLE
Corrupted pdf file of tree from .dist

### ISSUE THREAD

**Issue by DiedeMaas** [fgvieira/ngsDist#2]
Hi,

I have been following the ngsTools/TUTORIAL, in particular to try and create a tree with FastMe from .dist data generated by ngsDist. The problem is that the pdf file that R plots is 'corrupted' and cannot be opened.

The commands from the tutorial that I have been following:

$NGSTOOLS/ngsDist/ngsDist -verbose 1 -geno Results/ALL.geno.gz -probs -n_ind 60 -n_sites $N_SITES -labels Data/pops.label -o Results/ALL.dist -n_threads 4

$FASTME -D 1 -i Results/ALL.dist -o Results/ALL.tree -m b -n b

Rscript -e 'library(ape); library(phangorn); pdf(file="Results/ALL.tree.pdf"); plot(read.tree("Results/ALL.tree"), cex=0.5)

Have you seen this issue before? Is there a clue on how I might solve this?

Thanks,
Diede

**Comment by fgvieira** [comment]
Hi Diede,

without seeing the files, it is a bit difficult to see what is going on.
Can you open the tree file (Results/ALL.tree) on another program (e.g. MEGA) or website (e.g. www.http://phylo.io/)?
Can you also attach the distance file you got here so I can have a look?

thanks,
FGV

**Comment by DiedeMaas** [comment]
Hi,

Thank you for your very swift answer! I tried to reinstall and run this again, but I came upon the same error - unfortunately. Hence my response was a bit delayed. 

As you suggested, I tried to compute my .tree file in phylo.io and there it did work! For MEGA I was unsure how to deal with the .tree format. Is it a Newick file? Then I need to convert it.

I have added my distance file which I converted to a .txt so it could be uploaded here.
[Brachidontes.txt](https://github.com/fgvieira/ngsDist/files/410978/Brachidontes.txt)

Best,
Diede

**Comment by fgvieira** [comment]
Hi Diede,

I tried reproducing your commands and all worked fine... Since you say the PDF was corrupted, maybe try updating R and the ape/phangorn packages. That said, the R line provided is just for demostration purposes, as there are much better software to render phylogenetic trees both offline (e.g. Figtree) and online (e.g. iTOL). I'd suggest you use one of those instead..

Cheers,
FGV

PS - the file you get from FastME is already in Newick format (even though it is called .tree), so you can directly open it on MEGA.

**Comment by DiedeMaas** [comment]
Hi mr. Vieira,

Ah, thank you so much for the effort! I will try again using the other
programs you mentioned.

Thank you again for your help,

Cheers, Diede

2016-08-15 20:51 GMT+02:00 Filipe G. Vieira notifications@github.com:
